### ISSUE TITLE
Flutter 3 changes

### ISSUE THREAD

**Issue by Sesa1988** [LinusU/flutter_web_auth#117]
Flutters API for widget binding changed and we need probably a small update to prevent a failed build.
Should probably be the same error for all platforms.

<img width="1294" alt="image" src="https://user-images.githubusercontent.com/26410357/167947697-f91da752-bb81-4063-abb7-2c67bb42d1b4.png">

**Comment by rienkkk** [comment]
Same error. The ! should be removed from WidgetBinding.instance. Since Flutter 3.0 it can't be null anymore.

**Comment by noga-dev** [comment]
You can override the pubspec to use my branch for now while we wait for #118 to be merged:

```yaml
flutter_web_auth:
  git:
     url: https://github.com/noga-dev/flutter_web_auth.git
     ref: ee3c26a530a625c3cab7e0c45cc30316c8b4b64c
```
