### ISSUE TITLE
Support for more native platforms (MacOS, Windows, Linux)

### ISSUE THREAD

**Issue by eldadfux** [LinusU/flutter_web_auth#22]
I Really loved this plugin, great work @LinusU. It would be great to see support for more platforms as Flutter is rising to become the leading SDK for cross-platform development.

I think support for macOS, Windows, and Linux for a start would be really helpful. I would have loved to help with this one, but I have no native development experience in any of these platforms.

I saw there is already a PR #20 trying to add macOS support, would be great to see more platforms soon.

**Comment by LinusU** [comment]
I've been doing some preliminary research on how to add Windows & Linux support. As far as I can tell, there isn't really an equivalent to an SFAuthenticationSession on these platforms, but I think that we could provide something similar.

There is already #74 open for Linux support, but I believe that it takes the wrong approach since it shows its own WebView instead of integrating with the user's browser. This means that the user won't be logged in to the services, which I believe the point of this package in. (I think that the other approach is better suited for the flutter_webview package)

My idea is roughly this, which has to be done independently for Windows & Linux. (and potentially for macOS as well if the users default browser isn't Safari)

1. Register the app (or probably, a small shim that sends the result to the app) as the protocol handler for `callbackScheme`
2. Detect the default browser
3. Launch the browser with appropriate flags to show the authentication window
4. Wait for the callback from the browser

I think that a good approach for developing this would be:

1. Callback proof of concept:
  1. Create a small binary that writes it arguments into file
  2. Manually register this binary as the protocol handler for any protocol
  3. Manually click a link to this protocol in Chrome/Firefox/Edge
  4. Verify that the full url was written to file
  5. Create a Flutter app and use it instead of the small binary
  6. See if there is a way to get the link via an event, or if it launches a new instance of the Flutter app
2. Popup proof of concept:
  1. Read the documentation on flags for Chrome/Firefox/Edge
  2. Figure out how to launch a new window, preferably without chrome, to a specific url
  3. Figure out how/if we can close this window programmatically
  4. Try this out together with callback proof of concept
3. Put everything together:
  1. Set up a new example app for this platform
  2. Create a new platform file in the library
  3. Implement the steps from 1 & 2
  4. Test it

**Comment by masewo** [comment]
@LinusU For Windows and Linux I am using a different approach:
i. Start a HttpServer that listens on localhost
ii. Launch url with url_launcher
iii. Fetch redirect url and serve some HTML content like: Authenticated! You can close this tab.
Downside of this approach is that there will a useless tab left open for the user. This behaviour can also be seen on other applications (IntelliJ / Github Login).

**Comment by Jon-Salmon** [comment]
I have produced a Windows implementation (https://github.com/Jon-Salmon/flutter_web_auth/tree/windows-implementation) but creating a PR is currently blocked by #98 

If anybody wants to use this in the meantime, this is what you would need:
```
dependencies:
  flutter_web_auth:
    git:
      url: https://github.com/Jon-Salmon/flutter_web_auth.git
      ref: windows-implementation
      path: flutter_web_auth

dependency_overrides:
  flutter_web_auth_platform_interface:
    git:
      url: https://github.com/Jon-Salmon/flutter_web_auth.git
      ref: windows-implementation
      path: flutter_web_auth_platform_interface
  flutter_web_auth_windows:
    git:
      url: https://github.com/Jon-Salmon/flutter_web_auth.git
      ref: windows-implementation
      path: flutter_web_auth_window
```
