### ISSUE TITLE
[Samsung S3, S4]Handshake error in client (OS Error: CERTIFICATE_VERIFY_FAILED: self signed certificate in certificate chain(handshake.cc:352))

### ISSUE THREAD

**Issue by jingjiewei** [LinusU/flutter_web_auth#5]
Plugin works well under Huawei P10, but got an Handshake error in Samsung S3, S4.

Error message: 
E/flutter (19262):      [ERROR:flutter/lib/ui/ui_dart_state.cc(148)] Unhandled Exception: HandshakeException: Handshake error in client (OS Error:
E/flutter (19262): 	CERTIFICATE_VERIFY_FAILED: self signed certificate in certificate chain(handshake.cc:352))

flutter doctor: 
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, v1.5.4-hotfix.2, on Microsoft Windows [Version 10.0.17134.885], locale en-NZ)

[√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[!] Android Studio (version 3.2)
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
[√] VS Code (version 1.35.0)
[√] VS Code, 32-bit edition (version 1.30.2)
[√] Connected device (1 available)

project config: 

```
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

  http: ^0.12.0+2
  provider: ^3.0.0+1
  get_it: ^1.0.3+2
  moor_flutter: ^1.5.0
  flutter_web_auth: ^0.1.1
  logger: ^0.7.0+2
  shared_preferences: ^0.5.3+2
  barcode_scan:  ^1.0.0
```
